import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import 'intl-tel-input/build/css/intlTelInput.css';
import "./globals.css";
import ScrollToTop from "@/components/scrolltotop";



const figtree = Figtree({
  weight: ['400', '700'], 
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "House",
  description: "Generated by create next app",
};
// style={{fontFamily: figtree.style.fontFamily}}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={figtree.className}
      >
        <ScrollToTop/>
        {children}
      </body>
    </html>
  );
}
